# Generated by Django 2.2.8 on 2020-03-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200319_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_Address',
            new_name='apartment_address',
        ),
    ]
