# Generated by Django 2.2.8 on 2020-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
